- name: Create System Alarm Definitions
  monasca_alarm_definition:
    name: "{{item.name}}"
    expression: "{{item.expression}}"
    keystone_token: "{{default_notification.keystone_token}}"
    match_by: "{{item.match_by | default(['hostname']) }}"
    monasca_api_url: "{{default_notification.monasca_api_url}}"
    alarm_actions:
      - "{{default_notification.notification_method_id}}"
    ok_actions:
      - "{{default_notification.notification_method_id}}"
    undetermined_actions:
      - "{{default_notification.notification_method_id}}"
  with_items:
    - { name: "Host Alive Alarm", expression: "host_alive_status > 0"}
    - { name: "Http Status Alarm", expression: "http_status > 0", match_by: ["service", "hostname"] }
    - { name: "High CPU usage", expression: "avg(cpu.idle_perc) < 10 times 3" }
    - { name: "Disk Inode Usage", expression: "disk.inode_used_perc > 90" }
    - { name: "Disk Usage", expression: "disk.space_used_perc > 90" }
    - { name: "Memory usage", expression: "avg(mem.usable_perc) < 10 times 3" }
    - { name: "Network Errors", expression: "net.in_errors >5 or net.out_errors > 5" }
    - { name: "Process not found", expression: "process.pid_count < 1", match_by: ["process_name", "hostname"] }
